var hierarchy =
[
    [ "Attributes", "class_attributes.html", null ],
    [ "PlayerInput.CharacterControlsActions", "struct_player_input_1_1_character_controls_actions.html", null ],
    [ "Conference", "class_conference.html", null ],
    [ "ConferenceFactory", "class_conference_factory.html", null ],
    [ "Document", "class_document.html", null ],
    [ "DocumentGenerator", "class_document_generator.html", null ],
    [ "PlayerInput.ICharacterControlsActions", "interface_player_input_1_1_i_character_controls_actions.html", null ],
    [ "IDisposable", null, [
      [ "PlayerInput", "class_player_input.html", null ]
    ] ],
    [ "IInputActionCollection2", null, [
      [ "PlayerInput", "class_player_input.html", null ]
    ] ],
    [ "IInteractable", "interface_i_interactable.html", [
      [ "Astronaut_Interaction_Tutorial", "class_astronaut___interaction___tutorial.html", null ],
      [ "ConferenceInteractor", "class_conference_interactor.html", null ],
      [ "DocumentDispenser", "class_document_dispenser.html", null ],
      [ "LibraryInteractor", "class_library_interactor.html", null ],
      [ "MetadataManager", "class_metadata_manager.html", null ],
      [ "ServerInteractor", "class_server_interactor.html", null ],
      [ "WorkspaceInteraction", "class_workspace_interaction.html", null ]
    ] ],
    [ "ILoggable", "interface_i_loggable.html", [
      [ "Logger", "class_logger.html", null ]
    ] ],
    [ "Library", "class_library.html", null ],
    [ "MonoBehaviour", null, [
      [ "AnimationAndMovementController", "class_animation_and_movement_controller.html", null ],
      [ "Astronaut_Interaction_Tutorial", "class_astronaut___interaction___tutorial.html", null ],
      [ "AudioPlayer", "class_audio_player.html", null ],
      [ "CameraFollow", "class_camera_follow.html", null ],
      [ "ConferenceInteractor", "class_conference_interactor.html", null ],
      [ "ConferenceManager", "class_conference_manager.html", null ],
      [ "DocStackPlayer", "class_doc_stack_player.html", null ],
      [ "DocumentDispenser", "class_document_dispenser.html", null ],
      [ "DocumentStacker", "class_document_stacker.html", null ],
      [ "DoorInteraction", "class_door_interaction.html", null ],
      [ "DoubleDoorController", "class_double_door_controller.html", null ],
      [ "EndScript", "class_end_script.html", null ],
      [ "Highlight", "class_highlight.html", null ],
      [ "InteractionPromptUI", "class_interaction_prompt_u_i.html", null ],
      [ "Interactor", "class_interactor.html", null ],
      [ "IntroScene", "class_intro_scene.html", null ],
      [ "Inventory", "class_inventory.html", null ],
      [ "LevelManager", "class_level_manager.html", null ],
      [ "LibraryInteractor", "class_library_interactor.html", null ],
      [ "LibraryManager", "class_library_manager.html", null ],
      [ "Logger", "class_logger.html", null ],
      [ "MainPlayer", "class_main_player.html", null ],
      [ "MetadataManager", "class_metadata_manager.html", null ],
      [ "ObjectFadeManager", "class_object_fade_manager.html", null ],
      [ "ObjectFader", "class_object_fader.html", null ],
      [ "Oiiaoi", "class_oiiaoi.html", null ],
      [ "PauseMenu", "class_pause_menu.html", null ],
      [ "PlanetMenu", "class_planet_menu.html", null ],
      [ "PlayerLevelManager", "class_player_level_manager.html", null ],
      [ "PrincipalMenu", "class_principal_menu.html", null ],
      [ "QuestionMarkController", "class_question_mark_controller.html", null ],
      [ "Rocket", "class_rocket.html", null ],
      [ "RoomManagement", "class_room_management.html", null ],
      [ "RoomManager", "class_room_manager.html", null ],
      [ "ScriptReader", "class_script_reader.html", null ],
      [ "ServerInteractor", "class_server_interactor.html", null ],
      [ "ServerManager", "class_server_manager.html", null ],
      [ "SkyManager", "class_sky_manager.html", null ],
      [ "Stats", "class_stats.html", null ],
      [ "TaskManager", "class_task_manager.html", null ],
      [ "TaskUI", "class_task_u_i.html", null ],
      [ "Viktor", "class_viktor.html", null ],
      [ "WorkspaceInteraction", "class_workspace_interaction.html", null ]
    ] ],
    [ "Observer", "interface_observer.html", [
      [ "PlayerLevelManager", "class_player_level_manager.html", null ],
      [ "RoomManager", "class_room_manager.html", null ]
    ] ],
    [ "Planet", "class_planet.html", null ],
    [ "PlanetsAPI", "class_planets_a_p_i.html", null ],
    [ "PlayerData", "class_player_data.html", null ],
    [ "Rock", "class_rock.html", null ],
    [ "RocksAPI", "class_rocks_a_p_i.html", null ],
    [ "Skill", "class_skill.html", [
      [ "Agility", "class_agility.html", null ],
      [ "Calculator", "class_calculator.html", null ],
      [ "Crosser", "class_crosser.html", null ],
      [ "HawkEye", "class_hawk_eye.html", null ],
      [ "Intuition", "class_intuition.html", null ],
      [ "Ironclad", "class_ironclad.html", null ],
      [ "Mediator", "class_mediator.html", null ],
      [ "Memory", "class_memory.html", null ],
      [ "Organizer", "class_organizer.html", null ],
      [ "Phoenix", "class_phoenix.html", null ],
      [ "Reflexes", "class_reflexes.html", null ],
      [ "Serenity", "class_serenity.html", null ],
      [ "Vigilance", "class_vigilance.html", null ],
      [ "Vision", "class_vision.html", null ]
    ] ],
    [ "SkillFactory", "class_skill_factory.html", null ],
    [ "Task", "class_task.html", null ]
];